name: Build

on: 
  push:
    branches: 
    - master
  release:
    types:
    - published

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo ${{ github.ref }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        name: Install packages
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
        name: Run tests
      - run: npm test
        if: runner.os != 'Linux'
        name: Run tests
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/releases/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        name: Install packages
      - run: npm version --git-tag-version false --commit-hooks false ${{ github.event.release.tag_name }}
        name: Update version in package.json
      - run: npm run deploy
        name: Publish to marketplace
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN }}


