name: Publish Extension

on:
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm install -g vsce
    - run: vsce publish -p ${{ secrets.PUBLISHER_TOKEN }}
