name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm install -g vsce
      - run: npm version --git-tag-version false --commit-hooks false ${{ github.event.release.tag_name }}
      - run: xvfb-run -a vsce publish -p ${{ secrets.PUBLISHER_TOKEN }}
